### ISSUE TITLE
ERROR in ./src/other.ts

### ISSUE THREAD

**Issue by iZaiZaiA** [wechat-miniprogram/miniprogram-custom-component#19]
执行npm run dev命令后，控制台报错。

```
ERROR in ./src/other.ts
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
No ESLint configuration found.

    at Config.getLocalConfigHierarchy (/Users/xxxx/wechat/component/node_modules/eslint/lib/config.js:268:39)
    at Config.getConfigHierarchy (/Users/xxxx/wechat/component/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/Users/xxxx/wechat/component/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/Users/xxxx/wechat/component/node_modules/eslint/lib/config.js:342:29)
    at processText (/Users/xxxx/wechat/component/node_modules/eslint/lib/cli-engine.js:181:33)
    at CLIEngine.executeOnText (/Users/xxxx/wechat/component/node_modules/eslint/lib/cli-engine.js:690:40)
    at lint (/Users/xxxx/wechat/component/node_modules/eslint-loader/index.js:278:17)
    at Object.module.exports (/Users/xxxx/wechat/component/node_modules/eslint-loader/index.js:273:21)

ERROR in ./src/index.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 1)
No ESLint configuration found.

    at Config.getLocalConfigHierarchy (/Users/xxxx/wechat/component/node_modules/eslint/lib/config.js:268:39)
    at Config.getConfigHierarchy (/Users/xxxx/wechat/component/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/Users/xxxx/wechat/component/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/Users/xxxx/wechat/component/node_modules/eslint/lib/config.js:342:29)
    at processText (/Users/xxxx/wechat/component/node_modules/eslint/lib/cli-engine.js:181:33)
    at CLIEngine.executeOnText (/Users/xxxx/wechat/component/node_modules/eslint/lib/cli-engine.js:690:40)
    at lint (/Users/xxxx/wechat/component/node_modules/eslint-loader/index.js:278:17)
    at Object.module.exports (/Users/xxxx/wechat/component/node_modules/eslint-loader/index.js:273:21)

ERROR in ./src/lib.ts
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 2)
No ESLint configuration found.

    at Config.getLocalConfigHierarchy (/Users/xxxx/wechat/component/node_modules/eslint/lib/config.js:268:39)
    at Config.getConfigHierarchy (/Users/xxxx/wechat/component/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/Users/xxxx/wechat/component/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/Users/xxxx/wechat/component/node_modules/eslint/lib/config.js:342:29)
    at processText (/Users/xxxx/wechat/component/node_modules/eslint/lib/cli-engine.js:181:33)
    at CLIEngine.executeOnText (/Users/xxxx/wechat/component/node_modules/eslint/lib/cli-engine.js:690:40)
    at lint (/Users/xxxx/wechat/component/node_modules/eslint-loader/index.js:278:17)
    at Object.module.exports (/Users/xxxx/wechat/component/node_modules/eslint-loader/index.js:273:21)

```

电脑系统版本：MACOS 10.15.7

系统node版本：v12.16.3

使用方式：从github上下载zip，然后解压到目录里，执行npm install后，再执行npm run dev就有了以上报错。

执行npm install时，有以下报错：

```

> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxxx/wechat/component/node_modules/fsevents
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

```

**Comment by iZaiZaiA** [comment]
我换成   miniprogram init --type custom-component  的方式后，就没问题了。。。
