### ISSUE TITLE
npm run test fail

### ISSUE THREAD

**Issue by kaiye** [wechat-miniprogram/miniprogram-custom-component#4]
I cloned this repository to my disk, after running the following commands
```
npm i
npm run dev
npm run build
npm test
```
It threw an error
```
 FAIL  test/wx.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'callDefinitionFilter' of undefined

      43 |   'open-data', 'web-view', 'ad'
      44 | ].forEach(name => {
    > 45 |   jComponent.register({
         |              ^
      46 |     id: name,
      47 |     tagName: `wx-${name}`,
      48 |     template: '<slot/>'

      at ComponentManager.registerToExparser (node_modules/j-component/src/componentmanager.js:245:46)
      at new ComponentManager (node_modules/j-component/src/componentmanager.js:85:29)
      at Object.register (node_modules/j-component/src/index.js:11:28)
      at register (tools/test/helper.js:45:14)
          at Array.forEach (<anonymous>)
      at Object.forEach (tools/test/helper.js:44:3)
      at Object.require (test/utils.js:1:18)
      at Object.require (test/wx.test.js:1:11)
```

**Comment by JuneAndGreen** [comment]
try to remove node_modules and reinstall the dependencies ?

**Comment by kaiye** [comment]
It works good now, could you please add a `.travis.yml` to this project and a build status icon in the README.md file?

```
language: node_js
node_js:
  - "10"
```

**Comment by JuneAndGreen** [comment]
Yes, it is in the plan.
